# Generated by Django 5.2.7 on 2025-10-10 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_entrenador', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_contratacion', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_socio', models.CharField(max_length=10, unique=True)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('domicilio', models.CharField(max_length=200)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('tipo_socio', models.CharField(choices=[('interno', 'Interno (Suscripción Gimnasio)'), ('externo', 'Externo (Pago por Clase)')], default='externo', max_length=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo/Vencido')], default='activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_clase', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField()),
                ('duracion_minutos', models.IntegerField(default=60)),
                ('max_participantes', models.IntegerField(default=20)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.entrenador')),
                ('participantes', models.ManyToManyField(blank=True, related_name='clases_inscritas', to='gimnasio.socio')),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_suscripcion', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('mensual', 'Mensual ($500)'), ('trimestral', 'Trimestral ($1500)'), ('anual', 'Anual ($6000)')], max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('socio', models.ForeignKey(limit_choices_to={'tipo_socio': 'interno'}, on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='gimnasio.socio')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pago', models.CharField(max_length=10, unique=True)),
                ('tipo_pago', models.CharField(choices=[('gimnasio', 'Suscripción Gimnasio'), ('clase', 'Pago por Clase')], max_length=10)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(blank=True, max_length=20, null=True)),
                ('clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gimnasio.clase')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gimnasio.socio')),
                ('suscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gimnasio.suscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_inscripcion', models.CharField(max_length=10, unique=True)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.clase')),
                ('pago_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gimnasio.pago')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.socio')),
            ],
            options={
                'unique_together': {('socio', 'clase')},
            },
        ),
    ]
