# Generated by Django 5.2.7 on 2025-10-10 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='dni',
        ),
    ]
