# Generated by Django 5.2.7 on 2025-10-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0002_remove_socio_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='id_clase',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='id_entrenador',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='inscripcionclase',
            name='id_inscripcion',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_pago',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='id_suscripcion',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
