# Generated by Django 5.2.7 on 2025-10-25 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0004_producto_ventaproducto_ventaitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VentaProducto',
            new_name='Caja',
        ),
        migrations.CreateModel(
            name='CajaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('producto', 'Venta de productos'), ('mensualidad', 'Mensualidad'), ('clase', 'Clase'), ('otro', 'Otro')], default='producto', max_length=20)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov_caja', to='gimnasio.socio')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov_caja', to='gimnasio.caja')),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'ordering': ['-fecha'],
            },
        ),
    ]
