# Generated by Django 5.2.7 on 2025-10-28 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0007_alter_socio_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcionclase',
            name='pago_asociado',
        ),
        migrations.AddField(
            model_name='cajamovimiento',
            name='inscripcion_clase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago_clase', to='gimnasio.inscripcionclase'),
        ),
        migrations.AddField(
            model_name='cajamovimiento',
            name='suscripcion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago_suscripcion', to='gimnasio.suscripcion'),
        ),
        migrations.AddField(
            model_name='inscripcionclase',
            name='movimiento_caja',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripcion_clase_asociada', to='gimnasio.cajamovimiento'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='movimiento_caja',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suscripcion_asociada', to='gimnasio.cajamovimiento'),
        ),
        migrations.AlterField(
            model_name='cajamovimiento',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov_caja_socio', to='gimnasio.socio'),
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
